name: CI

on: 
  push:
    branches:
      - main

#run it only when node project changes
    paths: 
      - "nodejs-docker-cicd-pipeline/**"
      - ".github/workflows/ci.yml"
  
  pull_request:
    branches:
    - main

    paths: 
      - "nodejs-docker-cicd-pipeline/**"
      - ".github/workflows/ci.yml"

jobs:
  test:
    runs-on: ubuntu-latest

#my default working directory
    defaults: 
      run: 
        working-directory: nodejs-docker-cicd-pipeline

    steps:
      - name: Checkout COde
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: nodejs-docker-cicd-pipeline/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Login to dockerhub
        uses: docker/login-action@v3
        with: 
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}
      
      - name: Build docker image
        run: docker build -t subodhdhamala/nodejs-cicd-pipeline:latest .

      - name: Push docker image
        run: docker push subodhdhamala/nodejs-cicd-pipeline:latest